Sync with deb packages.
svn:r3888

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,9 +1,40 @@
-#!/bin/bash
-set -e 
+#!/bin/sh 
+set -e
 
 #DEBHELPER#
 
 . /usr/share/debconf/confmodule
 
-db_stop
+
+seen='false'
+askuser() {
+	db_get vidalia/info
+}
+
+if [ "$1" = "configure" ]; then
+	if dpkg -l tor > /dev/null 2>&1; then
+	    # installed
+	    if [ -e '/var/run/tor/tor.pid' ]; then
+		# and already running
+		askuser
+        	seen='true'
+		if [ "$RET" = "true" ]; then
+		    invoke-rc.d --force tor stop
+		fi
+	    fi
+	fi
+
+	if pgrep -x tor > /dev/null 2>&1; then 
+		# still running?? (e.g. chroot)
+    		if [ "$seen" = "false" ]; then
+			askuser
+			if [ "$RET" = "true" ]; then
+			    echo -n "Stopping tor daemon: "
+			    pkill -x tor > /dev/null && echo "tor." || echo 'Failed!'
+			fi
+		fi
+	fi
+	db_stop
+fi
+
 exit 0
